# initial trust value of each obstacle
obstacleInitTrust: 0.075

# cluster extraction settings
minBlobElements: 10
maxBlobElements: 500
blobMaxDistance: 0.1

# dimensions check
minWidth:   0.0
maxWidth:   0.5
minLength:  0.0
maxLength:  0.8

# pose covariance (x, y, z, roll, pitch, yaw)
pose_covariance: [ 0.04,    0,    0,    0,    0,    0,
                      0, 0.04,    0,    0,    0,    0,
                      0,    0, 0.04,    0,    0,    0,
                      0,    0,    0,    0,    0,    0,
                      0,    0,    0,    0,    0,    0,
                      0,    0,    0,    0,    0,    0]

# twist covariance  (x, y, z, roll, pitch, yaw)
twist_covariance: [    0,    0,    0,    0,    0,    0,
                       0,    0,    0,    0,    0,    0,
                       0,    0,    0,    0,    0,    0,
                       0,    0,    0,    0,    0,    0,
                       0,    0,    0,    0,    0,    0,
                       0,    0,    0,    0,    0,    0]
